### ISSUE TITLE
Dialog for selecting folders for photo synchronization selects folders randomly

### ISSUE THREAD

**Issue by rbxrt** [Infomaniak/android-kDrive#1560]
**Description**
I want to enable photo synchronization and I already have several folders with pictures on my phone which seems to cause some issues.

**Steps to reproduce**

**Issue 1:** When I want to set up photo synchronization, the folder selection dialog remains empty at first.
So I press the close icon to return to the configuration page for photo synchronization.
Now all available folders are suddenly selected.

If I want to narrow down the selection, I can do this using the toggles. I deactivate all the folders that I don't want to synchronize. Then I click the close icon again to go back.

**Issue 2 (very annoying):** My folder selection is not handled correctly. Instead, random folders are selected or deselected for synchronization. Every time I open the folder selection dialog again, other folders are selected. As soon as I scroll through the folder selection dialog, the selected folders also change.

**Expected behavior**
Folder selection works as expected: No random selection.
Ideally: A "Toggle all" button is available to easily narrow down the folders I want to synchronize.

**Smartphone:**
 - Device: Samsung Galaxy S25
 - Android version: Android 15
 - App version: 5.4.1 (Build 50400101)

**Comment by Tri4c3** [comment]
the same problem... the Beta apk te hsame problem.

**Comment by JorisBodin** [comment]
Hello,

I've managed to reproduce it, on the very first load the page remains empty, if you quit and come back it works.

Do you still have the loader at the top of the page when you change the folder selection?

**Comment by rbxrt** [comment]
Yes every time I open the page for selecting folders, a loading indicator appears for a moment.
And every time I scroll through the list of folders, the toggles change.

**Comment by JorisBodin** [comment]
Fixed, thank you for the feedback :)
Available in the next version

https://github.com/Infomaniak/android-kDrive/pull/1562
https://github.com/Infomaniak/android-kDrive/pull/1563
https://github.com/Infomaniak/android-kDrive/pull/1564

**Comment by rbxrt** [comment]
Got the updated version today but unfortunately it's not yet fixed.
The behavior has been improved, but not completely resolved. 

Current behaviour: As I said, I have many folders to choose from. However, I can apparently only select the folders in the visible area. As soon as I scroll down (and scroll up again), the selection is gone again.
If I want to select many folders, I necessarily have to scroll. However, when confirming the selected folders, only the last few folders that were in the visible area are selected.

**Comment by rbxrt** [comment]
It seems to work fine with the latest update :)

**Comment by JorisBodin** [comment]
Ah, so you weren't in the beta!

Perfect!
